name: Deploy FastAPI to VPS

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed  # Deploy only when PR is merged

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          APP_DIR: "/home/${{ secrets.VPS_USER }}/babciagpt/DiagramGenieService"
        run: |
          # Save the private key and set permissions
          echo "$SSH_KEY" > private_key
          chmod 600 private_key
          
          # SSH into VPS and pull latest code
          ssh -i private_key -o StrictHostKeyChecking=no -p 12092 $SSH_USER@$SSH_HOST << EOF
            # Navigate to app directory or clone repo if not exists
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/BabciaGPT/DiagramGenieService.git $APP_DIR
            fi
          
            cd $APP_DIR
            git pull origin main
          
            # Set up Python environment
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
          
            # Kill existing Uvicorn process (if running)
            pkill -f "uvicorn main:app" || true
          
            # Start FastAPI with Uvicorn in the background
            nohup venv/bin/uvicorn main:app --host 0.0.0.0 --port 42092 --env-file .env > app.log 2>&1 &
          EOF
